definitions:
  contracts.CreateBrokerRequest:
    properties:
      description:
        type: string
      host:
        type: string
      name:
        type: string
      password:
        type: string
      port:
        type: integer
      user:
        type: string
    required:
    - description
    - host
    - name
    - password
    - port
    - user
    type: object
  contracts.PaginatedResult-entities_BrokerEntity:
    properties:
      pageNumber:
        type: integer
      pageSize:
        type: integer
      result:
        items:
          $ref: '#/definitions/entities.BrokerEntity'
        type: array
      totalItems:
        type: integer
    type: object
  dto.ImportUserRequest:
    properties:
      BrokerId:
        type: integer
      Username:
        type: string
    required:
    - BrokerId
    - Username
    type: object
  entities.BrokerEntity:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      description:
        type: string
      host:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      port:
        type: integer
      updatedAt:
        type: string
      user:
        type: string
    type: object
  entities.UserEntity:
    properties:
      Broker:
        $ref: '#/definitions/entities.BrokerEntity'
      BrokerId:
        type: integer
      PasswordHash:
        type: string
      Username:
        type: string
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      updatedAt:
        type: string
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
info:
  contact: {}
paths:
  /broker:
    get:
      consumes:
      - application/json
      description: Retrieve a paginated list of cluster that the user has access
      parameters:
      - default: 1
        in: query
        name: PageNumber
        required: true
        type: integer
      - default: 10
        in: query
        name: PageSize
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/contracts.PaginatedResult-entities_BrokerEntity'
      summary: Retrieve a list of rabbitmq clusters registered
      tags:
      - Broker
    post:
      consumes:
      - application/json
      description: Create a new <b>RabbitMQ</b> broker. The credential provider must
        be valid and the cluster operational
      parameters:
      - description: Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/contracts.CreateBrokerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
      summary: Register a new RabbitMQ Broker
      tags:
      - Broker
  /broker/{brokerId}:
    delete:
      consumes:
      - application/json
      description: Soft delete a broker will not completly erase from database, but
        will not show up anymore in the
      parameters:
      - description: Id of a broker to be soft deleted
        in: path
        name: brokerId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            type: boolean
      summary: Soft delete a broker
      tags:
      - Broker
    get:
      consumes:
      - application/json
      description: Retrieve a single rabbitmq cluster
      parameters:
      - description: Id of a broker to be retrived
        in: path
        name: brokerId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.BrokerEntity'
      summary: Retrieve a single rabbitmq cluster
      tags:
      - Broker
  /broker/exists:
    get:
      consumes:
      - application/json
      description: Check if exists an rabbitmq cluster with host es
      parameters:
      - in: query
        name: Host
        required: true
        type: string
      - in: query
        name: Port
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Verify if exists a rabbitmqcluster
      tags:
      - Broker
  /user:
    post:
      consumes:
      - application/json
      description: Create a new <b>RabbitMQ User mirror</b> from the broker. The user
        must exist in the cluster, the login and hashpassword will be imported
      parameters:
      - description: Request
        in: body
        name: ImportUserRequest
        required: true
        schema:
          $ref: '#/definitions/dto.ImportUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: number
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Syncronize a existing RabbitMQ user from the broker.
      tags:
      - User
  /user/{userId}:
    delete:
      consumes:
      - application/json
      description: Delete a mirrored user from the registry, the user will not be
        deleted from the cluster
      parameters:
      - description: User id registered
        in: path
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete a mirror user
      tags:
      - User
    get:
      consumes:
      - application/json
      description: Recovery the details of a specific mirror user that is already
        imported from the cluster
      parameters:
      - description: User id registered
        in: path
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.UserEntity'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Retrieve a mirror user from broker
      tags:
      - User
swagger: "2.0"
