import { getClientSideLocale, getClientSideTranslation } from "@/i18n";
import "./globals.css";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  
  return (
    <html lang="en">
      <NextIntlClientProvider
        locale={getClientSideLocale()}
        messages={await getClientSideTranslation()}
      >
        <body className={inter.className}>{children}</body>
      </NextIntlClientProvider>
    </html>
  );
}
