import Header from "@/components/Header/Header";
import Sidebar from "@/components/Sidebar/Sidebar";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "ORabbit | Dashboard",
  description: "Generated by create next app",
};

async function NewClusterLayout({ children }: { children: React.ReactNode }) {
  return <div className="h-full w-full">{children}</div>;
}

export default NewClusterLayout;
