import Heading from "@/components/Heading/Heading";
import { Mail } from "lucide-react";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "ORabbit | Queues",
  description: "Generated by create next app",
};
function QueuesPage() {
  return <div></div>;
}

export default QueuesPage;
