version: "3.8"
services:
  database:
    image: mysql:8.0
    container_name: db_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL=1
    volumes:
      - db:/var/lib/mysql
      - ./initialize_database.sql:/docker-entrypoint-initdb.d/init.sql
  rabbitmq-blue:
    image: rabbitmq:management
    container_name: rabbitmq-blue
    environment:
      - RABBITMQ_DEFAULT_USER=radmin
      - RABBITMQ_DEFAULT_PASS=radmin
    ports:
      - "5671:5672"
      - "15671:15672"
  rabbitmq-green:
    image: rabbitmq:management
    container_name: rabbitmq-green
    environment:
      - RABBITMQ_DEFAULT_USER=radmin
      - RABBITMQ_DEFAULT_PASS=radmin
      - RABBIT_MQ_DEFINITIONS_FILE=/etc/rabbitmq/definitions.json
    ports:
      - "5672:5672"
      - "15672:15672"
  rabbitmq-red:
    image: rabbitmq:management
    container_name: rabbitmq-red
    environment:
      - RABBITMQ_DEFAULT_USER=radmin
      - RABBITMQ_DEFAULT_PASS=radmin
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - ./definitions/red_rabbit.json:/etc/rabbitmq/definitions.json
      
networks:
  orabbit:
    driver: host
volumes:
  db:
    driver: local
    name: mysql-volume
  rabbit:
    driver: local
    name: rabbitmq-volume
