import Header from "@/components/Header/Header";
import Sidebar from "@/components/Sidebar/Sidebar";
import ImportClusterProvider from "@/providers/import-cluster-provider";
import { fetchAllClusters } from "@/actions/cluster";
import { Metadata } from "next";
import React from "react";
import { RabbitMqCluster } from "@/types";

export const metadata: Metadata = {
  title: "ORabbit | Dashboard",
  description: "Generated by create next app",
};

async function DashboardLayout({ children }: { children: React.ReactNode }) {
  const cluster = await fetchAllClusters();
  return (
    <div className="grid grid-cols-12 h-screen">
      <div className="col-span-2">
        <Sidebar Clusters={cluster} />
      </div>
      <div className="flex col-span-10 flex-col w-full h-screen">
        <div className="w-full h-[7vh]">
          <Header />
        </div>
        <div className="px-10 py-5 h-screen">
          {" "}
          <ImportClusterProvider />
          {children}
        </div>
      </div>
    </div>
  );
}

export default DashboardLayout;
