name: Jest Unit Tests and Code Coverage

on:
  push:

  pull_request:
    branches:
      - 'feature/*'
    paths:
      - 'src/web/client/**'

jobs:
  test-and-coverage:
    name: Test and Code Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Escolha a versão do Node.js adequada para o seu projeto

      - name: Install dependencies
        run: |
          cd src/web/client
          npm install

      - name: Run Jest tests and generate coverage
        run: |
          cd src/web/client
          npm run test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: .src/web/client/coverage/lcov.info
