name: Test Inventory Service
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build and test
        run: |
          cd src/services/inventory
          go build
          go test -v -coverprofile=coverage.txt ./...

      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          file: ./src/services/inventory/coverage.txt

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
          SONAR_GO_COVERAGE_REPORT_PATH: src/services/inventory/coverage.txt
