import Header from "@/components/Header/Header";
import Sidebar from "@/components/Sidebar/Sidebar";
import ImportClusterProvider from "@/providers/import-cluster-provider";
import { fetchAllClusters } from "@/services/cluster";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "ORabbit | Dashboard",
  description: "Generated by create next app",
};

async function DashboardLayout({ children }: { children: React.ReactNode }) {
  const cluster = await fetchAllClusters();

  return (
    <div className="flex flex-row h-screen">
      <div className="w-[25vw] md:w-[20vw] h-screen">
        <Sidebar Clusters={cluster.result} />
      </div>
      <div className="flex flex-col w-full h-full">
        <div className="w-full h-[7vh]">
          <Header />
        </div>
        <div className="px-10 py-5 h-full">
          {" "}
          <ImportClusterProvider />
          {children}
        </div>
      </div>
    </div>
  );
}

export default DashboardLayout;
